# fly.toml app configuration file generated for ddb on 2023-06-06T12:48:08+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ddb"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
